CREATE DATABASE sql_powerbi_project;

use sql_powerbi_project;

SELECT * FROM customer;

-- What is the total revenue generated by male vs. female customers
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Which customers used a discount but still spent more than the average purchase amount
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (
       SELECT AVG(purchase_amount) 
       FROM customer
);

-- Which are the top 5 products with the highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating),2) AS avg_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;

-- compare the average purchase amounts between standard and express shipping. 
SELECT shipping_type, AVG(purchase_amount) 
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

-- Do subscribed customers spend more? compare average spend and total revenue 
-- between subscribers and non-subscribers. 
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY avg_spend, total_revenue DESC;

-- Which 5 products have the highest percentage of purchases with discount applied
SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100, 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Segment customers into new, Returning and loyal based on their total number of previous
-- purchases and show the count of each segment

WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
	END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) AS 'No.of customer'
FROM customer_type
GROUP BY customer_segment;

-- what are the top 3 most purchased products within each category
WITH item_counts AS (
     SELECT category, item_purchased,
            COUNT(customer_id) AS total_orders,
     ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS prod_rank
     FROM customer
     GROUP BY category, item_purchased
)
SELECT prod_rank, category, item_purchased, total_orders
FROM item_counts
WHERE prod_rank <= 3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- What is the revenue contribution of each age group

SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;






















